### ISSUE TITLE
YANG Guidelines for developing future multi-technology single instance modes and scenarios

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/transport-nbi#108]
We need to decide how/where to document our YANG guidelines. Maybe a Wiki on the CCAMP area is sufficient? Currently, we have provided some guidelines in specific documents. We will start writing down thoughts informally, and then decided where to store in the future. 

YANG Updates include:
- Network Type
- Node Type
- Link Type
- LTP Type
- Bandwidth 
- Label Range

**Comment by italobusi** [comment]
Guidelines under development in PR #118 

Few questions for further discussion:
- the use of the (technology) choice with label-start/label-end/label-step is not aligned with the case+when discussion in Netmod WG (RFC8407-bis): should we reconsider these guidelines as well?
- should we develop a JSON example for the multi-layer topology in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10871263/MLN.Topologies.v2.pptx
