### ISSUE TITLE
Move definitions from [TE-TUTORIAL] to [TE-TUNNEL]

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/transport-nbi#77]
The following definitions in [TE-TUTORIAL] are worth being moved to [TE-TUNNEL]:

- TE Tunnel
- TE Tunnel Segment
- TE Tunnel Hand-off

If this is done, the Applicability Statement I-D could have only an informative reference to [TE-TUTORIAL], otherwise the reference should become normative

- [x] @italobusi : Send a mail to the TEAS WG mailing list proposing to move these definitions from [TE-TUTORIAL] to [TE-TUNNEL]: https://github.com/danielkinguk/transport-nbi/issues/77#issuecomment-516918329

- [x] https://github.com/tsaad-dev/te/issues/59

**Comment by italobusi** [comment]
Mail sent to TEAS WG: https://mailarchive.ietf.org/arch/msg/teas/H2Pd3sym1SkvS1YBW9mhZzqSspg

**Comment by italobusi** [comment]
WG last call comment: https://mailarchive.ietf.org/arch/msg/ccamp/lzOGtZK7QMTUBIILCI3DZoZzOqA/

OLD

   TE Tunnel: As defined in [TE-TUTORIAL], it is a connection-oriented
   service provided by a layer network of delivery of a client's data
   between source and destination tunnel termination points.

   TE Tunnel Segment: As defined in [TE-TUTORIAL], it is a part of a
   multi-domain TE tunnel that spans.

   TE Tunnel Hand-off: As defined in [TE-TUTORIAL], it is an access
   link or inter-domain link by which a multi-domain TE tunnel enters
   or exits a given network domain.

   Note - The three definitions above are currently in [TE-TUTORIAL]
   but it is expected that they will be moved to [TE-TUNNEL]. When this
   happens, the reference will be updated and the [TE-TUTORIAL]
   reference will be downgraded to Informative.

NEW

   TE Tunnel: As defined in [TE-TUNNEL], it is a connection-oriented
   service provided by a layer network of delivery of a client's data
   between source and destination tunnel termination points. See also
   [TE-TUTORIAL].

   TE Tunnel Segment: As defined in [TE-TUNNEL], it is a part of a
   multi-domain TE tunnel that spans. See also [TE-TUTORIAL].

   TE Tunnel Hand-off: It is an access link or inter-domain link by
   which a multi-domain TE tunnel enters or exits a given network
   domain. See also [TE-TUTORIAL].

**Comment by italobusi** [comment]
> WG last call comment: https://mailarchive.ietf.org/arch/msg/ccamp/lzOGtZK7QMTUBIILCI3DZoZzOqA/
> 
> OLD
> 
> TE Tunnel: As defined in [TE-TUTORIAL], it is a connection-oriented
> service provided by a layer network of delivery of a client's data
> between source and destination tunnel termination points.
> 
> TE Tunnel Segment: As defined in [TE-TUTORIAL], it is a part of a
> multi-domain TE tunnel that spans.
> 
> TE Tunnel Hand-off: As defined in [TE-TUTORIAL], it is an access
> link or inter-domain link by which a multi-domain TE tunnel enters
> or exits a given network domain.
> 
> Note - The three definitions above are currently in [TE-TUTORIAL]
> but it is expected that they will be moved to [TE-TUNNEL]. When this
> happens, the reference will be updated and the [TE-TUTORIAL]
> reference will be downgraded to Informative.
> 
> NEW
> 
> TE Tunnel: As defined in [TE-TUNNEL], it is a connection-oriented
> service provided by a layer network of delivery of a client's data
> between source and destination tunnel termination points. See also
> [TE-TUTORIAL].
> 
> TE Tunnel Segment: As defined in [TE-TUNNEL], it is a part of a
> multi-domain TE tunnel that spans. See also [TE-TUTORIAL].
> 
> TE Tunnel Hand-off: It is an access link or inter-domain link by
> which a multi-domain TE tunnel enters or exits a given network
> domain. See also [TE-TUTORIAL].

Sergio's comment: https://mailarchive.ietf.org/arch/msg/ccamp/O1fNkfgZljBppiekwpcHj7P2a3s/

Only one comment: the TE tunnel hand-off in Tutorial draft, is defined  for the "point",
I mean :
TE tunnel hand-off point - an access link or inter-domain link by which a multi-domain TE tunnel enters or exits a given network domain, in conjunction with a layer network resource (such as a wavelength channel or ODUk container) allocated on the access/inter-domain link for the TE tunnel

**Comment by italobusi** [comment]
Proposed rephrase for the tunnel hand-off to address @sergiobelotti comment:

> TE Tunnel Hand-off: It is an access or inter-domain LTP by
> which a multi-domain TE tunnel enters or exits a given network
> domain. See also [TE-TUTORIAL].
> 

@sergiobelotti : is it ok for you?

**Comment by sergiobelotti** [comment]
> Proposed rephrase for the tunnel hand-off to address @sergiobelotti comment:
> 
> > TE Tunnel Hand-off: It is an access or inter-domain LTP by
> > which a multi-domain TE tunnel enters or exits a given network
> > domain. See also [TE-TUTORIAL].
> 
> @sergiobelotti : is it ok for you?

@italobusi : Thanks Italo, I'm ok with your proposed text. We can close the comment for me.

**Comment by italobusi** [comment]
Closed with PR #92
