### ISSUE TITLE
Use a new attribute for dependency Tunnel

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/transport-nbi#79]
Update the JSON code examples () when a new attribute is defined for dependency Tunnel

- [x] #91 
- [x] check that the text in the draft is consistent with the updated JSON examples (https://github.com/danielkinguk/transport-nbi/issues/79#issuecomment-902615437)

References:
- https://github.com/danielkinguk/transport-nbi/pull/78#issuecomment-542646360
- https://github.com/tsaad-dev/te/issues/53

**Comment by italobusi** [comment]
**2019-10-16 DT Call**

This issue is not blocking for WG LC

**Comment by italobusi** [comment]
https://github.com/tsaad-dev/te/issues/53 have been closed: the draft and JSON code can be updated accordingly

**Comment by italobusi** [comment]
PR #91 updates the JSON examples

@italobusi : check that the text in the draft is consistent with the updated JSON examples

**Comment by italobusi** [comment]
There is no text in the draft the describe the administrative auto state so no need to change the text but only the JSON file

If useful, some description can be added to section 5.2.2:

OLD

```
   Appendix B.2.2 provides the detailed JSON code ("mpi1-odu2-tunnel-
   config.json") describing how the setup of this ODU2 (Head Segment)
   Tunnel can be requested by the MDSC, using the [TE-TUNNEL] and
   [OTN-TUNNEL] YANG models at MPI1.

```
NEW

```
   Since there is not enough information about which client traffic
   should be steered to the OTN Tunnel, the ODU2 (HEad Segment)
   Tunnel is setup with the administrative auto state, as defined in
   [TE-TUNNEL].

   Appendix B.2.2 provides the detailed JSON code ("mpi1-odu2-tunnel-
   config.json") describing how the setup of this ODU2 (Head Segment)
   Tunnel can be requested by the MDSC, using the [TE-TUNNEL] and
   [OTN-TUNNEL] YANG models at MPI1.

```

@danielkinguk : what do you think?

**Comment by danielkinguk** [comment]
Looks good, thanks Italo.
