### ISSUE TITLE
Section 4.6 Notification Section Cleanup/References

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/transport-nbi#84]
Section 4.6 is not clear to me. Should one refer to RFC 8640, 8641, and 8650 as far as the datastore update is concerned? Clarify the term 'alarm', do you mean YANG notification or RFC 8623? This section needs some work.

- [x] #94

**Comment by danielkinguk** [comment]
New text in Section 4.

**Comment by italobusi** [comment]
Proposed reply:

Section 4.6 describes requirements for notifications and alarms at the NBI. RFC 8640, 8641, and 8650 as well as RFC8632 (rather that RFC8623), provides solutions based on YANG models defined by IETF. The analysis of these RFCs is outside the scope of this document as outlined in the last sentence of section 4.6.


- [ ] @italo Check definitions for notifications and alarm requirements? It  should be some ITU-T document.

**Comment by italobusi** [comment]
@danielkinguk : I think this issue has been closed, together with issue #94 by PR #92 

Please check and if you agree close this issue
