### ISSUE TITLE
JSON Tool for T-NBI I-D fails to run

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/transport-nbi#86]
> (RTG DIR Review)I tried to set up the docker validate tool as per https://github.com/GianmarcoBruno/json-yang ; I was not able to make it run and gave up after a while. :( The instruction on GitHub README.md does not match with what's in the docker image include the options.

See: #82 

- [ ] Replace the link in the I-D with a ling to the tagged release (https://github.com/GianmarcoBruno/json-yang/tree/1.0) to have a stable reference

**Comment by GianmarcoBruno** [comment]
Hi Daniel
I am going through the documentation to make it easier to use.
In the meantime all what you need to do is:

1. build the tool, e.g. assume version 1
  `` 
   docker build . -t xxx:1
``
2. create a bash function "validate" to make life easier and put it into your .bashrc so you :
``
   function validate() {
    docker run --rm -it --mount type=bind,source="$(pwd)",target=/home/app xxx:1 "$@"
}
``
3. source .bashrc to make it available
4. Execute these commands to validate the T-NBI JSON examples:

```
validate -j  mpi1-epl-service-config.json -w config -m downloads -f
validate -j  mpi1-odu2-service-config.json -w config -m downloads -f
validate -j  mpi1-odu2-tunnel-config.json -w config -m downloads -f
validate -j mpi1-eth-topology.json -w data -m downloads -f
validate -j mpi1-otn-topology.json -w data -m downloads -f

**Comment by dhruvdhody** [comment]
root1@dd-linux:~/Documents/IETF/json-yang$ validate -j  mpi1-epl-service-config.json -w config -m downloads -f
2021-08-10 06:59:15,990 ERROR mpi1-epl-service-config.json: cannot find file 
warning: no models in downloads
no yang files in target to be evaluated

**Comment by italobusi** [comment]
Discussed offline with @dhruvdhody and @GianmarcoBruno 

Documentation corrected accordingly and repository tagged:

https://github.com/GianmarcoBruno/json-yang/tree/1.0

- [ ] Replace the link to the tagged release to have a stable reference

**Comment by danielkinguk** [comment]
Update reference, and move to appendix (if not there already).
