### ISSUE TITLE
Should the GitHub repo mentioned in the appendix moved under CCAMP WG's GitHub

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/transport-nbi#97]
> - Should the GitHub repo mentioned in the appendix moved under CCAMP WG's GitHub? That would be giving some control over the longtime validity of these URLs. Should they be added as references in the document as well.  

For further discussion on the mailing list

**Comment by italobusi** [comment]
Mail sent to CCAMP WG:

https://mailarchive.ietf.org/arch/msg/ccamp/Gq9-c_cH5-z0aMj6aDD1nMpTSeI/

Waiting for feedbacks from the CCAMP WG.

**Comment by danielkinguk** [comment]
Italo to check offline with Dieter and Gianmarco, it will not stop us submitting though,

**Comment by italobusi** [comment]
Repository forked under CCAMP WG:

https://github.com/ietf-ccamp-wg/json-yang
