### ISSUE TITLE
Speak to Dieter to move T-NBI repository to CCAMP 

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/transport-nbi#99]

**Comment by italobusi** [comment]
Feedbacks from @dieterbeller :


https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository

**Comment by danielkinguk** [comment]
Repository moved.
